# Generated by Django 4.1.7 on 2023-04-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeevento', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=50)),
                ('datahora_inicio', models.DateTimeField()),
                ('datahora_termino', models.DateTimeField()),
                ('descricao', models.TextField()),
            ],
        ),
    ]
