# Generated by Django 4.1.7 on 2023-04-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datahora_inicio',
            new_name='data_e_hora_inicio',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='datahora_termino',
            new_name='data_e_hora_termino',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='nomeevento',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='event',
            name='local',
            field=models.CharField(max_length=150),
        ),
    ]
