# Generated by Django 4.1.7 on 2023-04-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_rename_datahora_inicio_event_data_e_hora_inicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='nome',
            new_name='titulo',
        ),
    ]
