# Generated by Django 4.1.7 on 2023-04-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_rename_nome_event_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data_e_hora_inicio',
            new_name='data_e_hora',
        ),
        migrations.RemoveField(
            model_name='event',
            name='data_e_hora_termino',
        ),
    ]
