# Generated by Django 4.1.7 on 2023-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_rename_data_e_hora_inicio_event_data_e_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contato',
            field=models.CharField(default='Whatsapp:', max_length=150),
        ),
        migrations.AddField(
            model_name='event',
            name='max_ingressos',
            field=models.PositiveSmallIntegerField(default='50'),
        ),
    ]
