# Generated by Django 4.2.1 on 2023-05-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_voucher_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='check_in',
            field=models.CharField(choices=[(1, 'Unchecked'), (2, 'Checked')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
